// our most common game sizes:
// 640 x 480
// 640 x 384
// 480 x 320

var students = [{
    "group": "1",
    "firstname": "alicia",
    "lastname": "zhang",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "amaury",
    "lastname": "gallon",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "anna",
    "lastname": "allgeyer",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "ashlesha",
    "lastname": "sathe",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "athena",
    "lastname": "shen",
    "width": "480px",
    "height": "320px"
}, {
    "group": "1",
    "firstname": "carley",
    "lastname": "foss",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "caroline",
    "lastname": "chou",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "chelsea",
    "lastname": "roberts",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "emily",
    "lastname": "chien",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "gengwen",
    "lastname": "li",
    "width": "640px",
    "height": "480px"
}, {
    "group": "1",
    "firstname": "griffin",
    "lastname": "nuelle",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "ian",
    "lastname": "busby",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "justin",
    "lastname": "ling",
    "width": "480px",
    "height": "320px"
}, {
    "group": "1",
    "firstname": "kyra",
    "lastname": "smith",
    "width": "480px",
    "height": "320px"
}, {
    "group": "1",
    "firstname": "miki",
    "lastname": "kinoshita",
    "width": "480px",
    "height": "320px"
}, {
    "group": "1",
    "firstname": "parisa",
    "lastname": "bunysak",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "phoebe",
    "lastname": "hsu",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "raphael",
    "lastname": "hunt",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "saakhi",
    "lastname": "singh",
    "width": "640px",
    "height": "384px"
}, {
    "group": "1",
    "firstname": "hailey",
    "lastname": "shi",
    "width": "640px",
    "height": "328px"
}, {
    "group": "2",
    "firstname": "neythra",
    "lastname": "srinivasan",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "tiffany",
    "lastname": "kamimura",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "wenqi",
    "lastname": "snow-gao",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "amanda",
    "lastname": "glynn",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "audrey",
    "lastname": "yen",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "ben",
    "lastname": "ruggirello",
    "width": "640px",
    "height": "480px"
}, {
    "group": "2",
    "firstname": "charlee",
    "lastname": "liu",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "dillon",
    "lastname": "shipley",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "edvardas",
    "lastname": "cerneckis",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "emily",
    "lastname": "ho",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "ethan",
    "lastname": "yu",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "isabella",
    "lastname": "bertolini",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "katarina",
    "lastname": "compean",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "katie",
    "lastname": "brussell",
    "width": "640",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "mia",
    "lastname": "lipsitz",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "mimi",
    "lastname": "liu",
    "width": "640px",
    "height": "480px"
}, {
    "group": "2",
    "firstname": "monte",
    "lastname": "collins",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "natalie",
    "lastname": "morris",
    "width": "640px",
    "height": "384px"
}, {
    "group": "2",
    "firstname": "sebastian",
    "lastname": "moore",
    "width": "480px",
    "height": "320px"
}, {
    "group": "2",
    "firstname": "shendi",
    "lastname": "chen",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "alyssa",
    "lastname": "goh",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "amanda",
    "lastname": "dotter",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "angela",
    "lastname": "yang",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "anna",
    "lastname": "graffeo",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "calia",
    "lastname": "tong",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "dario",
    "lastname": "apodaca",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "domenico",
    "lastname": "delgado",
    "width": "480px",
    "height": "320px"
}, {
    "group": "3",
    "firstname": "emily",
    "lastname": "li",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "emma",
    "lastname": "doyle",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "gabriella",
    "lastname": "oconnor",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "gorkem",
    "lastname": "akdeniz-uysal",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "griffin",
    "lastname": "wells",
    "width": "480px",
    "height": "320px"
}, {
    "group": "3",
    "firstname": "jake",
    "lastname": "rasmussen",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "madeleine",
    "lastname": "rozansky",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "madyson",
    "lastname": "mcneill",
    "width": "640px",
    "height": "384px"
}, {
    "group": "3",
    "firstname": "melissa",
    "lastname": "kitagawa",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "ruohan",
    "lastname": "wu",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "selena",
    "lastname": "ke",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "taylor",
    "lastname": "reid",
    "width": "640px",
    "height": "480px"
}, {
    "group": "3",
    "firstname": "zoe",
    "lastname": "miles",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "abby",
    "lastname": "feinstein",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "adam",
    "lastname": "knauer",
    "width": "320px",
    "height": "480px"
}, {
    "group": "4",
    "firstname": "aisha",
    "lastname": "vohra",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "catherine",
    "lastname": "mao",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "dorothy",
    "lastname": "li",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "elise",
    "lastname": "wong",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "hazel",
    "lastname": "zhu",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "jigme",
    "lastname": "farber",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "kai",
    "lastname": "watanabe",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "katie",
    "lastname": "li",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "kelly",
    "lastname": "wang",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "maria",
    "lastname": "fagerstal",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "matthew",
    "lastname": "mccarthy",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "opal",
    "lastname": "lambert",
    "width": "640",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "prince-nikeyo",
    "lastname": "jones",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "ryan",
    "lastname": "greer",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "tiffany",
    "lastname": "chen",
    "width": "640px",
    "height": "384px"
}, {
    "group": "4",
    "firstname": "valerie",
    "lastname": "gwyneth",
    "width": "480px",
    "height": "320px"
}, {
    "group": "4",
    "firstname": "vivian",
    "lastname": "cheung",
    "width": "480px",
    "height": "320px"
}];